name: Deploy to Windows Server

on:
  push:
    branches:
      - final-working

jobs:
  deploy:
    runs-on: [self-hosted,ubuntu:latest]

    steps:

    - name: Generate SSH key pair
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: |
          ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Create SSH Key Pair
      run: |
        ssh-keygen -t ed25519 -N "" -f ./ssh_key
      shell: bash

    - name: Store SSH private key
      uses: appleboy/scp-action@master
      with:
        host: 16.170.210.149
        username: Administrator
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: ./ssh_key
        target: C:\
