name: Deploy to Windows Server

on:
  push:
    branches:
      - final-working

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project
      run: |
        expr 3 + 7 > math-homework.txt

       
    - name: Connect to Windows server and Deploy
      uses: peaceiris/actions-windows-ssh@v2
      with:
        host: 16.170.210.149
        user: Administrator
        password: 72sy!LuHfoRsVS=xhsl$.OWvBbEZTfrA
        source: math-homework.txt
        target: C:\
