name: Deploy to Windows server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and package
        run: |
          # run your build commands here
          # generate the artifacts in a directory, e.g. dist/
          mkdir dist
          echo "Hello, world!" > dist/hello.txt

      - name: Install WinRM
        run: |
          # Install WinRM client
          powershell.exe Install-Module -Name Microsoft.PowerShell.Collector -Force
          powershell.exe Install-Module -Name Microsoft.PowerShell.SecretManagement -Force
          powershell.exe Install-Module -Name Microsoft.PowerShell.SecretStore -Force

      - name: Deploy artifacts
        env:
          WINRM_HOST: ${{ secrets.WINRM_HOST }}
          WINRM_USER: ${{ secrets.WINRM_USER }}
          WINRM_PASSWORD: ${{ secrets.WINRM_PASSWORD }}
          WINRM_DESTINATION: 'C:\'
        run: |
          # Create WinRM session
          $securePassword = ConvertTo-SecureString $env:WINRM_PASSWORD -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ($env:WINRM_USER, $securePassword)
          $session = New-PSSession -ComputerName $env:WINRM_HOST -Credential $credential -Authentication Negotiate -UseSSL

          # Copy artifacts to destination
          Copy-Item -Path $env:GITHUB_WORKSPACE\dist\* -Destination $env:WINRM_DESTINATION -ToSession $session
