name: Deploy to Windows server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and package
        run: |
          # run your build commands here
          # generate the artifacts in a directory, e.g. dist/
          mkdir dist
          echo "Hello, world!" > dist/hello.txt


      - name: Install WinRM
        run: |
          if(!(Test-Path C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSRemoting)) {
          Enable-PSRemoting -Force
          }
          Get-Service -Name WinRM
          Enable-PSRemoting -Force
          Set-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System -Name LocalAccountTokenFilterPolicy -Value 1
          Restart-Service -Name WinRM

          

      - name: Deploy artifacts
        env:
          WINRM_HOST: "16.170.210.149"
          WINRM_USER: "Administrator"
          WINRM_PASSWORD: "72sy!LuHfoRsVS=xhsl$.OWvBbEZTfrA"
          WINRM_DESTINATION: 'C:\'
        run: |
          # Create WinRM session
          winrm s winrm/config/client '@{TrustedHosts="16.170.210.149"}'

          #Set-Item WSMan:\localhost\Client\TrustedHosts -Value $env:WINRM_HOST -Force
          #$session = New-PSSession -ComputerName $env:WINRM_HOST -Credential $credential
          #$session = New-PSSession -ComputerName $env:WINRM_HOST -Credential $credential -UseSSL


          $securePassword = ConvertTo-SecureString $env:WINRM_PASSWORD -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ($env:WINRM_USER, $securePassword)
          $session = New-PSSession -ComputerName $env:WINRM_HOST -Credential $credential

          # Copy artifacts to destination
          Copy-Item -Path $env:GITHUB_WORKSPACE\dist\* -Destination $env:WINRM_DESTINATION -ToSession $session
