name: Deploy to Windows Server

on:
  push:
    branches:
      - dummy

jobs:

  job_1:
    name: Add 3 and 7
    runs-on: windows-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: /tmp/math-homework.txt
          
  deploy:
    name: Deploy artifact to Windows Server
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install ansible

    - name: Deploy artifact
      env:
        ARTIFACT_NAME: math-homework.txt
        ARTIFACT_PATH: /tmp/math-homework.txt
        WINDOWS_HOST: 16.170.210.149
        WINDOWS_USER: Administrator
        WINDOWS_PASSWORD: 72sy!LuHfoRsVS=xhsl$.OWvBbEZTfrA
      run: |
        ansible-playbook deploy.yml

  deploy.yml:
    - name: Copy artifact to Windows Server
      hosts: windows-server
      gather_facts: no
      tasks:
        - name: Copy artifact to Windows Server
          win_copy:
            src: "{{ lookup('env', 'ARTIFACT_PATH') }}"
            dest: "C:\\{{ lookup('env', 'ARTIFACT_NAME') }}"
          register: copy_result

        - name: Display copy result
          debug:
            var: copy_result
