name: Deploy to Windows server
on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and package
        run: |
          # run your build commands here
          mkdir dist
          echo "Hello, world!" > hello.txt

        
      - name: Push artifacts
        uses: appleboy/scp-action@master
        with:
          host: "16.170.210.149"
          username: "Administrator"
          password: "72sy!LuHfoRsVS=xhsl$.OWvBbEZTfrA"
          source: hello.txt
          target: C:\

